export const DEFAULT_PERMISSIONS = {
  NATIONAL: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW",
    "VIEW_ALL_CENTERS", "CREATE_CENTER", "EDIT_CENTER", "APPROVE_CENTER", "DELETE_CENTER", "DELETE_ALL_CENTERS", "EXPORT_CENTERS",
    "VIEW_ADMIN_USERS", "VIEW_PUBLIC_USERS", "CREATE_USER", "EDIT_USER", "DELETE_USER", "TOGGLE_USER_ACTIVE", "RESET_USER_PASSWORD", "APPROVE_CHEF",
    "VIEW_COMPLAINTS", "MANAGE_COMPLAINTS", "ADD_COMPLAINT_NOTE", "VIEW_EVALUATIONS",
    "VIEW_GEO", "MANAGE_GEO", "IMPORT_CENTERS", "IMPORT_GEO", "EXPORT_GEO",
    "MANAGE_RBAC", "ASSIGN_RBAC_ROLES", "ACCESS_IMPORTS", "ACCESS_ROLES",
  ],
  REGULATOR: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW",
    "VIEW_ALL_CENTERS", "CREATE_CENTER", "EDIT_CENTER", "APPROVE_CENTER", "DELETE_CENTER", "DELETE_ALL_CENTERS", "EXPORT_CENTERS",
    "VIEW_ADMIN_USERS", "VIEW_PUBLIC_USERS", "CREATE_USER", "EDIT_USER", "DELETE_USER", "TOGGLE_USER_ACTIVE", "RESET_USER_PASSWORD", "APPROVE_CHEF",
    "VIEW_COMPLAINTS", "MANAGE_COMPLAINTS", "ADD_COMPLAINT_NOTE", "VIEW_EVALUATIONS",
    "VIEW_GEO", "MANAGE_GEO", "IMPORT_CENTERS", "IMPORT_GEO", "EXPORT_GEO",
    "ASSIGN_RBAC_ROLES", "ACCESS_IMPORTS", "ACCESS_ROLES",
  ],
  REGION: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW",
    "VIEW_ALL_CENTERS", "CREATE_CENTER", "EDIT_CENTER", "APPROVE_CENTER", "EXPORT_CENTERS",
    "VIEW_ADMIN_USERS", "CREATE_USER", "EDIT_USER", "TOGGLE_USER_ACTIVE", "RESET_USER_PASSWORD", "APPROVE_CHEF",
    "VIEW_COMPLAINTS", "ADD_COMPLAINT_NOTE", "VIEW_EVALUATIONS",
    "VIEW_GEO",
  ],
  DISTRICT: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW",
    "VIEW_ALL_CENTERS", "CREATE_CENTER", "EDIT_CENTER", "APPROVE_CENTER", "EXPORT_CENTERS",
    "VIEW_ADMIN_USERS", "CREATE_USER", "EDIT_USER", "TOGGLE_USER_ACTIVE", "RESET_USER_PASSWORD", "APPROVE_CHEF",
    "VIEW_COMPLAINTS", "ADD_COMPLAINT_NOTE", "VIEW_EVALUATIONS",
    "VIEW_GEO",
  ],
  ETABLISSEMENT: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW", "VIEW_NEARBY",
    "VIEW_ALL_CENTERS", "MANAGE_MY_CENTER",
    "VIEW_ADMIN_USERS", "CREATE_USER", "EDIT_USER", "TOGGLE_USER_ACTIVE", "RESET_USER_PASSWORD",
    "VIEW_EVALUATIONS",
  ],
  CHEF_ETABLISSEMENT: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW", "VIEW_NEARBY",
    "VIEW_ALL_CENTERS", "MANAGE_MY_CENTER",
    "VIEW_ADMIN_USERS", "CREATE_USER", "EDIT_USER", "TOGGLE_USER_ACTIVE", "RESET_USER_PASSWORD",
    "VIEW_COMPLAINTS", "ADD_COMPLAINT_NOTE", "VIEW_EVALUATIONS",
  ],
  SAMU: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW", "VIEW_NEARBY",
    "VIEW_EMERGENCY", "CREATE_EMERGENCY", "MANAGE_EMERGENCY", "VIEW_EMERGENCY_BASES", "MANAGE_EMERGENCY_BASES",
    "VIEW_ADMIN_USERS", "CREATE_USER", "EDIT_USER", "TOGGLE_USER_ACTIVE", "RESET_USER_PASSWORD",
  ],
  SAPEUR_POMPIER: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW", "VIEW_NEARBY",
    "VIEW_EMERGENCY", "CREATE_EMERGENCY", "MANAGE_EMERGENCY", "VIEW_EMERGENCY_BASES", "MANAGE_EMERGENCY_BASES",
    "VIEW_ADMIN_USERS", "CREATE_USER", "EDIT_USER", "TOGGLE_USER_ACTIVE", "RESET_USER_PASSWORD",
  ],
  POLICE: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW", "VIEW_NEARBY",
    "VIEW_SECURITY_ALERTS", "CREATE_SECURITY_ALERT", "MANAGE_SECURITY_ALERTS",
    "VIEW_ADMIN_USERS",
  ],
  GENDARMERIE: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW", "VIEW_NEARBY",
    "VIEW_SECURITY_ALERTS", "CREATE_SECURITY_ALERT", "MANAGE_SECURITY_ALERTS",
    "VIEW_ADMIN_USERS",
  ],
  PROTECTION_CIVILE: [
    "DASHBOARD_ADMIN", "VIEW_OVERVIEW", "VIEW_NEARBY",
    "VIEW_SECURITY_ALERTS", "CREATE_SECURITY_ALERT", "MANAGE_SECURITY_ALERTS",
    "VIEW_ADMIN_USERS",
  ],
  USER: [
    "VIEW_NEARBY", "SUBMIT_EVALUATION", "SUBMIT_COMPLAINT",
  ],
};
